!  This file was generated by kmcos (kinetic Monte Carlo of Systems)
!  written by Max J. Hoffmann mjhoffmann@gmail.com (C) 2009-2013.
!  The model was written by Juan M. Lorenzi.

!  This file is part of kmcos.
!
!  kmcos is free software; you can redistribute it and/or modify
!  it under the terms of the GNU General Public License as published by
!  the Free Software Foundation; either version 2 of the License, or
!  (at your option) any later version.
!
!  kmcos is distributed in the hope that it will be useful,
!  but WITHOUT ANY WARRANTY; without even the implied warranty of
!  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!  GNU General Public License for more details.
!
!  You should have received a copy of the GNU General Public License
!  along with kmcos; if not, write to the Free Software
!  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301
!  USA
!****h* kmcos/proclist
! FUNCTION
!    Implements the kMC process list.
!
!******


module proclist
use kind_values
use base, only: &
    update_accum_rate, &
    update_integ_rate, &
    determine_procsite, &
    update_clocks, &
    avail_sites, &
    null_species, &
    increment_procstat

use lattice, only: &
    default, &
    default_sc, &
    allocate_system, &
    nr2lattice, &
    lattice2nr, &
    add_proc, &
    can_do, &
    set_rate_const, &
    replace_species, &
    del_proc, &
    reset_site, &
    system_size, &
    spuck, &
    get_species


implicit none



 ! Species constants



integer(kind=iint), parameter, public :: nr_of_species = 3
integer(kind=iint), parameter, public :: Pt = 0
integer(kind=iint), parameter, public :: empty = 1
integer(kind=iint), parameter, public :: sub = 2
integer(kind=iint), public :: default_species = empty


! Process constants

integer(kind=iint), parameter, public :: Ads = 1
integer(kind=iint), parameter, public :: Ads_sub = 2
integer(kind=iint), parameter, public :: Des_000 = 3
integer(kind=iint), parameter, public :: Des_001 = 4
integer(kind=iint), parameter, public :: Des_002 = 5
integer(kind=iint), parameter, public :: Des_003 = 6
integer(kind=iint), parameter, public :: Des_004 = 7
integer(kind=iint), parameter, public :: Des_005 = 8
integer(kind=iint), parameter, public :: Des_006 = 9
integer(kind=iint), parameter, public :: Des_007 = 10
integer(kind=iint), parameter, public :: Des_008 = 11
integer(kind=iint), parameter, public :: Des_009 = 12
integer(kind=iint), parameter, public :: Des_010 = 13
integer(kind=iint), parameter, public :: Des_011 = 14
integer(kind=iint), parameter, public :: Des_012 = 15
integer(kind=iint), parameter, public :: Des_013 = 16
integer(kind=iint), parameter, public :: Des_014 = 17
integer(kind=iint), parameter, public :: Des_015 = 18


integer(kind=iint), parameter, public :: representation_length = 11
integer(kind=iint), public :: seed_size = 33
integer(kind=iint), public :: seed ! random seed
integer(kind=iint), public, dimension(:), allocatable :: seed_arr ! random seed


integer(kind=iint), parameter, public :: nr_of_proc = 18


contains

subroutine do_kmc_steps(n)

!****f* proclist/do_kmc_steps
! FUNCTION
!    Performs ``n`` kMC step.
!    If one has to run many steps without evaluation
!    do_kmc_steps might perform a little better.
!    * first update clock
!    * then configuration sampling step
!    * last execute process
!
! ARGUMENTS
!
!    ``n`` : Number of steps to run
!******
    integer(kind=ilong), intent(in) :: n

    integer(kind=ilong) :: i
    real(kind=rsingle) :: ran_proc, ran_time, ran_site
    integer(kind=iint) :: nr_site, proc_nr

    do i = 1, n
    call random_number(ran_time)
    call random_number(ran_proc)
    call random_number(ran_site)
    call update_accum_rate
    call update_clocks(ran_time)

    call update_integ_rate
    call determine_procsite(ran_proc, ran_site, proc_nr, nr_site)
!    print *, "PROCLIST/DO_KMC_STEP"
!    print *,"    PROCLIST/DO_KMC_STEP/RAN_TIME",ran_time
!    print *,"    PROCLIST/DO_KMC_STEP/RAN_PROC",ran_proc
!    print *,"    PROCLIST/DO_KMC_STEP/RAN_SITE",ran_site
!    print *,"PROCLIST/DO_KMC_STEP/NR_SITE", nr_site
!    print *,"PROCLIST/DO_KMC_STEP/PROC_NR", proc_nr       
    call run_proc_nr(proc_nr, nr_site)
    enddo

end subroutine do_kmc_steps

subroutine do_kmc_steps_time(t, n, num_iter)
!****f* proclist/do_kmc_steps_time
! FUNCTION
!    Performs a variable number of KMC steps to try to match the requested
!    simulation time as closely as possible without going over. This routine
!    always performs at least one KMC step before terminating.
!    * Determine the time step for the next process
!    * If the time limit is not exceeded, update clocks, rates, execute process,
!      etc.; otherwise, abort.
!    Ideally we would use state(seed_size) but that was not working, so hardcoded size.
!
! ARGUMENTS
!
!    ``t`` : Requested simulation time increment (input)
!    ``n`` : Maximum number of steps to run (input)
!    ``num_iter`` : the number of executed iterations (output)
!******
    use base, only: get_accum_rate
    real(kind=rdouble), intent(in) :: t
    integer(kind=ilong), intent(in) :: n
    integer(kind=ilong), intent(out) :: num_iter

    integer(kind=ilong) :: i
    real(kind=rsingle) :: ran_proc, ran_time, ran_site
    integer(kind=iint) :: nr_site, proc_nr
    integer(kind=iint) :: state(33)
    real(kind=rdouble) :: time_step, loop_kmc_time, accum_rate

    loop_kmc_time = 0
    num_iter = 0
    do i = 1, n
      call random_seed(get=state)
      call random_number(ran_time)
      call random_number(ran_proc)
      call random_number(ran_site)
      call update_accum_rate
      call get_accum_rate(0, accum_rate)
      time_step = -log(ran_time)/accum_rate
      if ((loop_kmc_time + time_step > t) .and. (num_iter > 0)) then
        call random_seed(put=state)
        exit
      else
        call update_clocks(ran_time)
        call update_integ_rate
        call determine_procsite(ran_proc, ran_site, proc_nr, nr_site)
        call run_proc_nr(proc_nr, nr_site)
        loop_kmc_time = loop_kmc_time + time_step
        num_iter = num_iter + 1
      end if
    end do
end subroutine do_kmc_steps_time

subroutine do_kmc_step()

!****f* proclist/do_kmc_step
! FUNCTION
!    Performs exactly one kMC step.
!    *  first update clock
!    *  then configuration sampling step
!    *  last execute process
!
! ARGUMENTS
!
!    ``none``
!******
    real(kind=rsingle) :: ran_proc, ran_time, ran_site
    integer(kind=iint) :: nr_site, proc_nr

    call random_number(ran_time)
    call random_number(ran_proc)
    call random_number(ran_site)
    call update_accum_rate
    call update_clocks(ran_time)

    call update_integ_rate
    call determine_procsite(ran_proc, ran_site, proc_nr, nr_site)
    call run_proc_nr(proc_nr, nr_site)
end subroutine do_kmc_step

subroutine get_next_kmc_step(proc_nr, nr_site)

!****f* proclist/get_next_kmc_step
! FUNCTION
!    Determines next step without executing it.
!    However, it changes the position in the random_number 
!    sequence. The python function for
!    model.get_next_kmc_step() should be used
!    as it makes additional function calls
!    to reset the random numbers.
!    Calling model.proclist.get_next_kmc_step()
!    is discouraged as that will call this subroutine
!    directly and will not reset the random numbers.
!
! ARGUMENTS
!
!    ``none``
!******
    real(kind=rsingle) :: ran_proc, ran_time, ran_site
    integer(kind=iint), intent(out) :: nr_site, proc_nr

    call random_number(ran_time)
    call random_number(ran_proc)
    call random_number(ran_site)
!    print *,"PROCLIST/GET_NEXT_KMC_STEP/RAN_TIME",ran_time
!    print *,"PROCLIST/GET_NEXT_KMC_STEP/RAN_PROC",ran_proc
!    print *,"PROCLIST/GET_NEXT_KMC_STEP/RAN_SITE",ran_site
    call update_accum_rate
    call determine_procsite(ran_proc, ran_site, proc_nr, nr_site)

!    print *,"PROCLIST/GET_NEXT_KMC_STEP/PROC_NR",proc_nr
end subroutine get_next_kmc_step

subroutine get_occupation(occupation)

!****f* proclist/get_occupation
! FUNCTION
!    Evaluate current lattice configuration and returns
!    the normalized occupation as matrix. Different species
!    run along the first axis and different sites run
!    along the second.
!
! ARGUMENTS
!
!    ``none``
!******
    ! nr_of_species = 3, spuck = 1
    real(kind=rdouble), dimension(0:2, 1:1), intent(out) :: occupation

    integer(kind=iint) :: i, j, k, nr, species

    occupation = 0

    do k = 0, system_size(3)-1
        do j = 0, system_size(2)-1
            do i = 0, system_size(1)-1
                do nr = 1, spuck
                    ! shift position by 1, so it can be accessed
                    ! more straightforwardly from f2py interface
                    species = get_species((/i,j,k,nr/))
                    if(species.ne.null_species) then
                    occupation(species, nr) = &
                        occupation(species, nr) + 1
                    endif
                end do
            end do
        end do
    end do

    occupation = occupation/real(system_size(1)*system_size(2)*system_size(3))
end subroutine get_occupation

subroutine init(input_system_size, system_name, layer, seed_in, no_banner)

!****f* proclist/init
! FUNCTION
!     Allocates the system and initializes all sites in the given
!     layer.
!
! ARGUMENTS
!
!    * ``input_system_size`` number of unit cell per axis.
!    * ``system_name`` identifier for reload file.
!    * ``layer`` initial layer.
!    * ``no_banner`` [optional] if True no copyright is issued.
!******
    integer(kind=iint), intent(in) :: layer, seed_in
    integer(kind=iint), dimension(3), intent(in) :: input_system_size

    character(len=400), intent(in) :: system_name

    logical, optional, intent(in) :: no_banner

    if (.not. no_banner) then
        print *, "+------------------------------------------------------------+"
        print *, "|                                                            |"
        print *, "| This kMC Model 'SOS_adsdes' was written by                 |"
        print *, "|                                                            |"
        print *, "|           Juan M. Lorenzi (jmlorenzi@gmail.com)            |"
        print *, "|                                                            |"
        print *, "| and implemented with the help of kmcos,                    |"
        print *, "| which is distributed under GNU/GPL Version 3               |"
        print *, "| (C) Max J. Hoffmann mjhoffmann@gmail.com                   |"
        print *, "|                                                            |"
        print *, "| kmcos is distributed in the hope that it will be useful    |"
        print *, "| but WITHOUT ANY WARRANTY; without even the implied         |"
        print *, "| warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR    |"
        print *, "| PURPOSE. See the GNU General Public License for more       |"
        print *, "| details.                                                   |"
        print *, "|                                                            |"
        print *, "| If using kmcos for a publication, attribution is           |"
        print *, "| greatly appreciated.                                       |"
        print *, "| Hoffmann, M. J., Matera, S., & Reuter, K. (2014).          |"
        print *, "| kmos: A lattice kinetic Monte Carlo framework.             |"
        print *, "| Computer Physics Communications, 185(7), 2138-2150.        |"
        print *, "|                                                            |"
        print *, "| Development https://github.com/kmcos/kmcos                 |"
        print *, "| Documentation https://kmcos.readthedocs.io                 |"
        print *, "| Reference https://dx.doi.org/10.1016/j.cpc.2014.04.003     |"
        print *, "|                                                            |"
        print *, "+------------------------------------------------------------+"
        print *, ""
        print *, ""
    endif
    call allocate_system(nr_of_proc, input_system_size, system_name)
    call initialize_state(layer, seed_in)
end subroutine init

function get_seed() result(state)
!****f* proclist/get_seed
! FUNCTION
!   Function to retrieve the state of the random number generator to
!    permit reproducible restart trajectories.
!
! ARGUMENTS
!
!    * None
!******
    integer :: state(33)
    call random_seed(get=state)
end function get_seed

subroutine put_seed(state)
!****f* proclist/put_seed
! FUNCTION
!    Subroutine to set the state of the random number generator to
!    permit reproducible restart trajectories.
!
! ARGUMENTS
!
!    * ``state`` an array of integers with the state of the random number
!    generator (input)
!******  
    integer, intent(in) :: state(33)
    call random_seed(put=state)
end subroutine put_seed 

function seed_gen(sd) result(sarr)
!****f* proclist/seed_gen
! FUNCTION
!    Function to transform a single number into a full set of integers
!    required for initializing the random number generator.
!
! ARGUMENTS
!
!    * ``sd`` an integer used to seed a simple random number generator
!    used to generate additional integers for seeding the production random
!    number generator (input)
!******


    integer, intent(in) :: sd
    integer(kind=ilong) :: s
    integer(kind=ilong) :: sarr(33)
    integer :: i

!Generate the state array with a simple linear congruential generator. The
!parameters for this generator are taken from the gfortran documentation on
!random_seed().

!Initialize the generator
    if (sd == 0) then
      s = 104729
    else
      s = mod(sd, 4294967296_ilong)
    end if

!Get values for the seed array
    do i =1, size(sarr)
      s = mod(s * 279470273_ilong, 4294967291_ilong)
      sarr(i) = int(mod(s, int(huge(0), ilong)), kind(0))
      s = mod(s, 4294967296_ilong)
    end do

end function seed_gen
subroutine initialize_state(layer, seed_in)

!****f* proclist/initialize_state
! FUNCTION
!    Initialize all sites and book-keeping array
!    for the given layer.
!
! ARGUMENTS
!
!    * ``layer`` integer representing layer
!******
    integer(kind=iint), intent(in) :: layer, seed_in

    integer(kind=iint) :: i, j, k, nr
    ! initialize random number generator
    allocate(seed_arr(seed_size))
    seed = seed_in
    seed_arr = seed_gen(seed)
    call random_seed(size=seed_size)
    call random_seed(put=seed_arr)
    deallocate(seed_arr)
    do k = 0, system_size(3)-1
        do j = 0, system_size(2)-1
            do i = 0, system_size(1)-1
                do nr = 1, spuck
                    call reset_site((/i, j, k, nr/), null_species)
                end do
                select case(layer)
                case (default)
                    call replace_species((/i, j, k, default_sc/), null_species, default_species)
                end select
            end do
        end do
    end do

    do k = 0, system_size(3)-1
        do j = 0, system_size(2)-1
            do i = 0, system_size(1)-1
                select case(layer)
                case(default)
                    call touchup_default_sc((/i, j, k, default_sc/))
                end select
            end do
        end do
    end do


end subroutine initialize_state

subroutine run_proc_nr(proc, nr_site)

!****f* proclist/run_proc_nr
! FUNCTION
!    Runs process ``proc`` on site ``nr_site``.
!
! ARGUMENTS
!
!    * ``proc`` integer representing the process number
!    * ``nr_site``  integer representing the site
!******
    integer(kind=iint), intent(in) :: proc
    integer(kind=iint), intent(in) :: nr_site

    integer(kind=iint), dimension(4) :: lsite

    call increment_procstat(proc)

    ! lsite = lattice_site, (vs. scalar site)
    lsite = nr2lattice(nr_site, :)

    select case(proc)
    case(Ads)
        call put_Pt_default_sc(lsite)

    case(Ads_sub)
        call put_Pt_default_sc(lsite)

    case(Des_000)
        call take_Pt_default_sc(lsite)

    case(Des_001)
        call take_Pt_default_sc(lsite)

    case(Des_002)
        call take_Pt_default_sc(lsite)

    case(Des_003)
        call take_Pt_default_sc(lsite)

    case(Des_004)
        call take_Pt_default_sc(lsite)

    case(Des_005)
        call take_Pt_default_sc(lsite)

    case(Des_006)
        call take_Pt_default_sc(lsite)

    case(Des_007)
        call take_Pt_default_sc(lsite)

    case(Des_008)
        call take_Pt_default_sc(lsite)

    case(Des_009)
        call take_Pt_default_sc(lsite)

    case(Des_010)
        call take_Pt_default_sc(lsite)

    case(Des_011)
        call take_Pt_default_sc(lsite)

    case(Des_012)
        call take_Pt_default_sc(lsite)

    case(Des_013)
        call take_Pt_default_sc(lsite)

    case(Des_014)
        call take_Pt_default_sc(lsite)

    case(Des_015)
        call take_Pt_default_sc(lsite)

    end select

end subroutine run_proc_nr

subroutine put_Pt_default_sc(site)

    integer(kind=iint), dimension(4), intent(in) :: site

    ! update lattice
    call replace_species(site, empty, Pt)

    ! disable affected processes
    if(avail_sites(Ads, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(Ads, site)
    endif

    if(avail_sites(Ads_sub, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(Ads_sub, site)
    endif

    if(avail_sites(Des_000, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (-1), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_000, site + (/0, 0, -1, 0/))
    endif

    if(avail_sites(Des_000, lattice2nr(site(1) + (-1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_000, site + (/-1, 0, 0, 0/))
    endif

    if(avail_sites(Des_000, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_000, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(Des_000, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_000, site + (/1, 0, 0, 0/))
    endif

    if(avail_sites(Des_000, lattice2nr(site(1) + (0), site(2) + (1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_000, site + (/0, 1, 0, 0/))
    endif

    if(avail_sites(Des_001, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (-1), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_001, site + (/0, 0, -1, 0/))
    endif

    if(avail_sites(Des_001, lattice2nr(site(1) + (-1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_001, site + (/-1, 0, 0, 0/))
    endif

    if(avail_sites(Des_001, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_001, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(Des_001, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_001, site + (/1, 0, 0, 0/))
    endif

    if(avail_sites(Des_002, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (-1), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_002, site + (/0, 0, -1, 0/))
    endif

    if(avail_sites(Des_002, lattice2nr(site(1) + (-1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_002, site + (/-1, 0, 0, 0/))
    endif

    if(avail_sites(Des_002, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_002, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(Des_002, lattice2nr(site(1) + (0), site(2) + (1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_002, site + (/0, 1, 0, 0/))
    endif

    if(avail_sites(Des_003, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (-1), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_003, site + (/0, 0, -1, 0/))
    endif

    if(avail_sites(Des_003, lattice2nr(site(1) + (-1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_003, site + (/-1, 0, 0, 0/))
    endif

    if(avail_sites(Des_003, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_003, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(Des_004, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (-1), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_004, site + (/0, 0, -1, 0/))
    endif

    if(avail_sites(Des_004, lattice2nr(site(1) + (-1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_004, site + (/-1, 0, 0, 0/))
    endif

    if(avail_sites(Des_004, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_004, site + (/1, 0, 0, 0/))
    endif

    if(avail_sites(Des_004, lattice2nr(site(1) + (0), site(2) + (1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_004, site + (/0, 1, 0, 0/))
    endif

    if(avail_sites(Des_005, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (-1), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_005, site + (/0, 0, -1, 0/))
    endif

    if(avail_sites(Des_005, lattice2nr(site(1) + (-1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_005, site + (/-1, 0, 0, 0/))
    endif

    if(avail_sites(Des_005, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_005, site + (/1, 0, 0, 0/))
    endif

    if(avail_sites(Des_006, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (-1), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_006, site + (/0, 0, -1, 0/))
    endif

    if(avail_sites(Des_006, lattice2nr(site(1) + (-1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_006, site + (/-1, 0, 0, 0/))
    endif

    if(avail_sites(Des_006, lattice2nr(site(1) + (0), site(2) + (1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_006, site + (/0, 1, 0, 0/))
    endif

    if(avail_sites(Des_007, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (-1), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_007, site + (/0, 0, -1, 0/))
    endif

    if(avail_sites(Des_007, lattice2nr(site(1) + (-1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_007, site + (/-1, 0, 0, 0/))
    endif

    if(avail_sites(Des_008, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (-1), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_008, site + (/0, 0, -1, 0/))
    endif

    if(avail_sites(Des_008, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_008, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(Des_008, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_008, site + (/1, 0, 0, 0/))
    endif

    if(avail_sites(Des_008, lattice2nr(site(1) + (0), site(2) + (1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_008, site + (/0, 1, 0, 0/))
    endif

    if(avail_sites(Des_009, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (-1), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_009, site + (/0, 0, -1, 0/))
    endif

    if(avail_sites(Des_009, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_009, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(Des_009, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_009, site + (/1, 0, 0, 0/))
    endif

    if(avail_sites(Des_010, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (-1), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_010, site + (/0, 0, -1, 0/))
    endif

    if(avail_sites(Des_010, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_010, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(Des_010, lattice2nr(site(1) + (0), site(2) + (1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_010, site + (/0, 1, 0, 0/))
    endif

    if(avail_sites(Des_011, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (-1), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_011, site + (/0, 0, -1, 0/))
    endif

    if(avail_sites(Des_011, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_011, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(Des_012, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (-1), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_012, site + (/0, 0, -1, 0/))
    endif

    if(avail_sites(Des_012, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_012, site + (/1, 0, 0, 0/))
    endif

    if(avail_sites(Des_012, lattice2nr(site(1) + (0), site(2) + (1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_012, site + (/0, 1, 0, 0/))
    endif

    if(avail_sites(Des_013, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (-1), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_013, site + (/0, 0, -1, 0/))
    endif

    if(avail_sites(Des_013, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_013, site + (/1, 0, 0, 0/))
    endif

    if(avail_sites(Des_014, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (-1), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_014, site + (/0, 0, -1, 0/))
    endif

    if(avail_sites(Des_014, lattice2nr(site(1) + (0), site(2) + (1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_014, site + (/0, 1, 0, 0/))
    endif

    if(avail_sites(Des_015, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (-1), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_015, site + (/0, 0, -1, 0/))
    endif

    ! enable affected processes
    select case(get_species(site + (/1, 0, 0, 0/)))
    case(empty)
        select case(get_species(site + (/0, 0, 1, 0/)))
        case(empty)
            select case(get_species(site + (/0, 1, 0, 0/)))
            case(empty)
                select case(get_species(site + (/-1, 0, 0, 0/)))
                case(empty)
                    select case(get_species(site + (/0, -1, 0, 0/)))
                    case(empty)
                        call add_proc(Des_000, site)
                    case(Pt)
                        call add_proc(Des_001, site)
                    end select

                case(Pt)
                    select case(get_species(site + (/0, -1, 0, 0/)))
                    case(empty)
                        call add_proc(Des_002, site)
                    case(Pt)
                        call add_proc(Des_003, site)
                    end select

                end select

            case(Pt)
                select case(get_species(site + (/-1, 0, 0, 0/)))
                case(empty)
                    select case(get_species(site + (/0, -1, 0, 0/)))
                    case(empty)
                        call add_proc(Des_004, site)
                    case(Pt)
                        call add_proc(Des_005, site)
                    end select

                case(Pt)
                    select case(get_species(site + (/0, -1, 0, 0/)))
                    case(empty)
                        call add_proc(Des_006, site)
                    case(Pt)
                        call add_proc(Des_007, site)
                    end select

                end select

            end select

        end select

    case(Pt)
        select case(get_species(site + (/1, 0, 1, 0/)))
        case(empty)
            select case(get_species(site + (/2, 0, 0, 0/)))
            case(empty)
                select case(get_species(site + (/1, 1, 0, 0/)))
                case(empty)
                    select case(get_species(site + (/1, -1, 0, 0/)))
                    case(empty)
                        call add_proc(Des_002, site + (/1, 0, 0, 0/))
                    case(Pt)
                        call add_proc(Des_003, site + (/1, 0, 0, 0/))
                    end select

                case(Pt)
                    select case(get_species(site + (/1, -1, 0, 0/)))
                    case(empty)
                        call add_proc(Des_006, site + (/1, 0, 0, 0/))
                    case(Pt)
                        call add_proc(Des_007, site + (/1, 0, 0, 0/))
                    end select

                end select

            case(Pt)
                select case(get_species(site + (/1, 1, 0, 0/)))
                case(empty)
                    select case(get_species(site + (/1, -1, 0, 0/)))
                    case(empty)
                        call add_proc(Des_010, site + (/1, 0, 0, 0/))
                    case(Pt)
                        call add_proc(Des_011, site + (/1, 0, 0, 0/))
                    end select

                case(Pt)
                    select case(get_species(site + (/1, -1, 0, 0/)))
                    case(empty)
                        call add_proc(Des_014, site + (/1, 0, 0, 0/))
                    case(Pt)
                        call add_proc(Des_015, site + (/1, 0, 0, 0/))
                    end select

                end select

            end select

        end select

        select case(get_species(site + (/0, 0, 1, 0/)))
        case(empty)
            select case(get_species(site + (/0, 1, 0, 0/)))
            case(empty)
                select case(get_species(site + (/-1, 0, 0, 0/)))
                case(empty)
                    select case(get_species(site + (/0, -1, 0, 0/)))
                    case(empty)
                        call add_proc(Des_008, site)
                    case(Pt)
                        call add_proc(Des_009, site)
                    end select

                case(Pt)
                    select case(get_species(site + (/0, -1, 0, 0/)))
                    case(empty)
                        call add_proc(Des_010, site)
                    case(Pt)
                        call add_proc(Des_011, site)
                    end select

                end select

            case(Pt)
                select case(get_species(site + (/-1, 0, 0, 0/)))
                case(empty)
                    select case(get_species(site + (/0, -1, 0, 0/)))
                    case(empty)
                        call add_proc(Des_012, site)
                    case(Pt)
                        call add_proc(Des_013, site)
                    end select

                case(Pt)
                    select case(get_species(site + (/0, -1, 0, 0/)))
                    case(empty)
                        call add_proc(Des_014, site)
                    case(Pt)
                        call add_proc(Des_015, site)
                    end select

                end select

            end select

        end select

    end select

    select case(get_species(site + (/-1, 1, 0, 0/)))
    case(empty)
        select case(get_species(site + (/0, 1, 0, 0/)))
        case(Pt)
            select case(get_species(site + (/0, 1, 1, 0/)))
            case(empty)
                select case(get_species(site + (/1, 1, 0, 0/)))
                case(empty)
                    select case(get_species(site + (/0, 2, 0, 0/)))
                    case(empty)
                        call add_proc(Des_001, site + (/0, 1, 0, 0/))
                    case(Pt)
                        call add_proc(Des_005, site + (/0, 1, 0, 0/))
                    end select

                case(Pt)
                    select case(get_species(site + (/0, 2, 0, 0/)))
                    case(empty)
                        call add_proc(Des_009, site + (/0, 1, 0, 0/))
                    case(Pt)
                        call add_proc(Des_013, site + (/0, 1, 0, 0/))
                    end select

                end select

            end select

        end select

        select case(get_species(site + (/-1, 0, 0, 0/)))
        case(Pt)
            select case(get_species(site + (/-1, 0, 1, 0/)))
            case(empty)
                select case(get_species(site + (/-2, 0, 0, 0/)))
                case(empty)
                    select case(get_species(site + (/-1, -1, 0, 0/)))
                    case(empty)
                        call add_proc(Des_008, site + (/-1, 0, 0, 0/))
                    case(Pt)
                        call add_proc(Des_009, site + (/-1, 0, 0, 0/))
                    end select

                case(Pt)
                    select case(get_species(site + (/-1, -1, 0, 0/)))
                    case(empty)
                        call add_proc(Des_010, site + (/-1, 0, 0, 0/))
                    case(Pt)
                        call add_proc(Des_011, site + (/-1, 0, 0, 0/))
                    end select

                end select

            end select

        end select

    case(Pt)
        select case(get_species(site + (/0, 1, 0, 0/)))
        case(Pt)
            select case(get_species(site + (/0, 1, 1, 0/)))
            case(empty)
                select case(get_species(site + (/1, 1, 0, 0/)))
                case(empty)
                    select case(get_species(site + (/0, 2, 0, 0/)))
                    case(empty)
                        call add_proc(Des_003, site + (/0, 1, 0, 0/))
                    case(Pt)
                        call add_proc(Des_007, site + (/0, 1, 0, 0/))
                    end select

                case(Pt)
                    select case(get_species(site + (/0, 2, 0, 0/)))
                    case(empty)
                        call add_proc(Des_011, site + (/0, 1, 0, 0/))
                    case(Pt)
                        call add_proc(Des_015, site + (/0, 1, 0, 0/))
                    end select

                end select

            end select

        end select

        select case(get_species(site + (/-1, 0, 0, 0/)))
        case(Pt)
            select case(get_species(site + (/-1, 0, 1, 0/)))
            case(empty)
                select case(get_species(site + (/-2, 0, 0, 0/)))
                case(empty)
                    select case(get_species(site + (/-1, -1, 0, 0/)))
                    case(empty)
                        call add_proc(Des_012, site + (/-1, 0, 0, 0/))
                    case(Pt)
                        call add_proc(Des_013, site + (/-1, 0, 0, 0/))
                    end select

                case(Pt)
                    select case(get_species(site + (/-1, -1, 0, 0/)))
                    case(empty)
                        call add_proc(Des_014, site + (/-1, 0, 0, 0/))
                    case(Pt)
                        call add_proc(Des_015, site + (/-1, 0, 0, 0/))
                    end select

                end select

            end select

        end select

    end select

    select case(get_species(site + (/0, -1, 0, 0/)))
    case(Pt)
        select case(get_species(site + (/0, -1, 1, 0/)))
        case(empty)
            select case(get_species(site + (/1, -1, 0, 0/)))
            case(empty)
                select case(get_species(site + (/-1, -1, 0, 0/)))
                case(empty)
                    select case(get_species(site + (/0, -2, 0, 0/)))
                    case(empty)
                        call add_proc(Des_004, site + (/0, -1, 0, 0/))
                    case(Pt)
                        call add_proc(Des_005, site + (/0, -1, 0, 0/))
                    end select

                case(Pt)
                    select case(get_species(site + (/0, -2, 0, 0/)))
                    case(empty)
                        call add_proc(Des_006, site + (/0, -1, 0, 0/))
                    case(Pt)
                        call add_proc(Des_007, site + (/0, -1, 0, 0/))
                    end select

                end select

            case(Pt)
                select case(get_species(site + (/-1, -1, 0, 0/)))
                case(empty)
                    select case(get_species(site + (/0, -2, 0, 0/)))
                    case(empty)
                        call add_proc(Des_012, site + (/0, -1, 0, 0/))
                    case(Pt)
                        call add_proc(Des_013, site + (/0, -1, 0, 0/))
                    end select

                case(Pt)
                    select case(get_species(site + (/0, -2, 0, 0/)))
                    case(empty)
                        call add_proc(Des_014, site + (/0, -1, 0, 0/))
                    case(Pt)
                        call add_proc(Des_015, site + (/0, -1, 0, 0/))
                    end select

                end select

            end select

        end select

    end select

    select case(get_species(site + (/0, 0, 1, 0/)))
    case(empty)
        call add_proc(Ads, site + (/0, 0, 1, 0/))
    end select


end subroutine put_Pt_default_sc

subroutine take_Pt_default_sc(site)

    integer(kind=iint), dimension(4), intent(in) :: site

    ! update lattice
    call replace_species(site, Pt, empty)

    ! disable affected processes
    if(avail_sites(Ads, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (1), site(4) + (0)), 2).ne.0)then
        call del_proc(Ads, site + (/0, 0, 1, 0/))
    endif

    if(avail_sites(Des_000, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(Des_000, site)
    endif

    if(avail_sites(Des_001, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(Des_001, site)
    endif

    if(avail_sites(Des_001, lattice2nr(site(1) + (0), site(2) + (1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_001, site + (/0, 1, 0, 0/))
    endif

    if(avail_sites(Des_002, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(Des_002, site)
    endif

    if(avail_sites(Des_002, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_002, site + (/1, 0, 0, 0/))
    endif

    if(avail_sites(Des_003, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(Des_003, site)
    endif

    if(avail_sites(Des_003, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_003, site + (/1, 0, 0, 0/))
    endif

    if(avail_sites(Des_003, lattice2nr(site(1) + (0), site(2) + (1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_003, site + (/0, 1, 0, 0/))
    endif

    if(avail_sites(Des_004, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(Des_004, site)
    endif

    if(avail_sites(Des_004, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_004, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(Des_005, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(Des_005, site)
    endif

    if(avail_sites(Des_005, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_005, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(Des_005, lattice2nr(site(1) + (0), site(2) + (1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_005, site + (/0, 1, 0, 0/))
    endif

    if(avail_sites(Des_006, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(Des_006, site)
    endif

    if(avail_sites(Des_006, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_006, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(Des_006, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_006, site + (/1, 0, 0, 0/))
    endif

    if(avail_sites(Des_007, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(Des_007, site)
    endif

    if(avail_sites(Des_007, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_007, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(Des_007, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_007, site + (/1, 0, 0, 0/))
    endif

    if(avail_sites(Des_007, lattice2nr(site(1) + (0), site(2) + (1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_007, site + (/0, 1, 0, 0/))
    endif

    if(avail_sites(Des_008, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(Des_008, site)
    endif

    if(avail_sites(Des_008, lattice2nr(site(1) + (-1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_008, site + (/-1, 0, 0, 0/))
    endif

    if(avail_sites(Des_009, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(Des_009, site)
    endif

    if(avail_sites(Des_009, lattice2nr(site(1) + (-1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_009, site + (/-1, 0, 0, 0/))
    endif

    if(avail_sites(Des_009, lattice2nr(site(1) + (0), site(2) + (1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_009, site + (/0, 1, 0, 0/))
    endif

    if(avail_sites(Des_010, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(Des_010, site)
    endif

    if(avail_sites(Des_010, lattice2nr(site(1) + (-1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_010, site + (/-1, 0, 0, 0/))
    endif

    if(avail_sites(Des_010, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_010, site + (/1, 0, 0, 0/))
    endif

    if(avail_sites(Des_011, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(Des_011, site)
    endif

    if(avail_sites(Des_011, lattice2nr(site(1) + (-1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_011, site + (/-1, 0, 0, 0/))
    endif

    if(avail_sites(Des_011, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_011, site + (/1, 0, 0, 0/))
    endif

    if(avail_sites(Des_011, lattice2nr(site(1) + (0), site(2) + (1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_011, site + (/0, 1, 0, 0/))
    endif

    if(avail_sites(Des_012, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(Des_012, site)
    endif

    if(avail_sites(Des_012, lattice2nr(site(1) + (-1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_012, site + (/-1, 0, 0, 0/))
    endif

    if(avail_sites(Des_012, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_012, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(Des_013, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(Des_013, site)
    endif

    if(avail_sites(Des_013, lattice2nr(site(1) + (-1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_013, site + (/-1, 0, 0, 0/))
    endif

    if(avail_sites(Des_013, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_013, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(Des_013, lattice2nr(site(1) + (0), site(2) + (1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_013, site + (/0, 1, 0, 0/))
    endif

    if(avail_sites(Des_014, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(Des_014, site)
    endif

    if(avail_sites(Des_014, lattice2nr(site(1) + (-1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_014, site + (/-1, 0, 0, 0/))
    endif

    if(avail_sites(Des_014, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_014, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(Des_014, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_014, site + (/1, 0, 0, 0/))
    endif

    if(avail_sites(Des_015, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(Des_015, site)
    endif

    if(avail_sites(Des_015, lattice2nr(site(1) + (-1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_015, site + (/-1, 0, 0, 0/))
    endif

    if(avail_sites(Des_015, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_015, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(Des_015, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_015, site + (/1, 0, 0, 0/))
    endif

    if(avail_sites(Des_015, lattice2nr(site(1) + (0), site(2) + (1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_015, site + (/0, 1, 0, 0/))
    endif

    ! enable affected processes
    select case(get_species(site + (/0, 0, -1, 0/)))
    case(sub)
        call add_proc(Ads_sub, site)
    case(Pt)
        call add_proc(Ads, site)
        select case(get_species(site + (/1, 0, -1, 0/)))
        case(empty)
            select case(get_species(site + (/0, 1, -1, 0/)))
            case(empty)
                select case(get_species(site + (/-1, 0, -1, 0/)))
                case(empty)
                    select case(get_species(site + (/0, -1, -1, 0/)))
                    case(empty)
                        call add_proc(Des_000, site + (/0, 0, -1, 0/))
                    case(Pt)
                        call add_proc(Des_001, site + (/0, 0, -1, 0/))
                    end select

                case(Pt)
                    select case(get_species(site + (/0, -1, -1, 0/)))
                    case(empty)
                        call add_proc(Des_002, site + (/0, 0, -1, 0/))
                    case(Pt)
                        call add_proc(Des_003, site + (/0, 0, -1, 0/))
                    end select

                end select

            case(Pt)
                select case(get_species(site + (/-1, 0, -1, 0/)))
                case(empty)
                    select case(get_species(site + (/0, -1, -1, 0/)))
                    case(empty)
                        call add_proc(Des_004, site + (/0, 0, -1, 0/))
                    case(Pt)
                        call add_proc(Des_005, site + (/0, 0, -1, 0/))
                    end select

                case(Pt)
                    select case(get_species(site + (/0, -1, -1, 0/)))
                    case(empty)
                        call add_proc(Des_006, site + (/0, 0, -1, 0/))
                    case(Pt)
                        call add_proc(Des_007, site + (/0, 0, -1, 0/))
                    end select

                end select

            end select

        case(Pt)
            select case(get_species(site + (/0, 1, -1, 0/)))
            case(empty)
                select case(get_species(site + (/-1, 0, -1, 0/)))
                case(empty)
                    select case(get_species(site + (/0, -1, -1, 0/)))
                    case(empty)
                        call add_proc(Des_008, site + (/0, 0, -1, 0/))
                    case(Pt)
                        call add_proc(Des_009, site + (/0, 0, -1, 0/))
                    end select

                case(Pt)
                    select case(get_species(site + (/0, -1, -1, 0/)))
                    case(empty)
                        call add_proc(Des_010, site + (/0, 0, -1, 0/))
                    case(Pt)
                        call add_proc(Des_011, site + (/0, 0, -1, 0/))
                    end select

                end select

            case(Pt)
                select case(get_species(site + (/-1, 0, -1, 0/)))
                case(empty)
                    select case(get_species(site + (/0, -1, -1, 0/)))
                    case(empty)
                        call add_proc(Des_012, site + (/0, 0, -1, 0/))
                    case(Pt)
                        call add_proc(Des_013, site + (/0, 0, -1, 0/))
                    end select

                case(Pt)
                    select case(get_species(site + (/0, -1, -1, 0/)))
                    case(empty)
                        call add_proc(Des_014, site + (/0, 0, -1, 0/))
                    case(Pt)
                        call add_proc(Des_015, site + (/0, 0, -1, 0/))
                    end select

                end select

            end select

        end select

    end select

    select case(get_species(site + (/-1, 1, 0, 0/)))
    case(empty)
        select case(get_species(site + (/-1, 0, 0, 0/)))
        case(Pt)
            select case(get_species(site + (/-1, 0, 1, 0/)))
            case(empty)
                select case(get_species(site + (/-2, 0, 0, 0/)))
                case(empty)
                    select case(get_species(site + (/-1, -1, 0, 0/)))
                    case(empty)
                        call add_proc(Des_000, site + (/-1, 0, 0, 0/))
                    case(Pt)
                        call add_proc(Des_001, site + (/-1, 0, 0, 0/))
                    end select

                case(Pt)
                    select case(get_species(site + (/-1, -1, 0, 0/)))
                    case(empty)
                        call add_proc(Des_002, site + (/-1, 0, 0, 0/))
                    case(Pt)
                        call add_proc(Des_003, site + (/-1, 0, 0, 0/))
                    end select

                end select

            end select

        end select

        select case(get_species(site + (/0, 1, 0, 0/)))
        case(Pt)
            select case(get_species(site + (/0, 1, 1, 0/)))
            case(empty)
                select case(get_species(site + (/1, 1, 0, 0/)))
                case(empty)
                    select case(get_species(site + (/0, 2, 0, 0/)))
                    case(empty)
                        call add_proc(Des_000, site + (/0, 1, 0, 0/))
                    case(Pt)
                        call add_proc(Des_004, site + (/0, 1, 0, 0/))
                    end select

                case(Pt)
                    select case(get_species(site + (/0, 2, 0, 0/)))
                    case(empty)
                        call add_proc(Des_008, site + (/0, 1, 0, 0/))
                    case(Pt)
                        call add_proc(Des_012, site + (/0, 1, 0, 0/))
                    end select

                end select

            end select

        end select

    case(Pt)
        select case(get_species(site + (/0, 1, 0, 0/)))
        case(Pt)
            select case(get_species(site + (/0, 1, 1, 0/)))
            case(empty)
                select case(get_species(site + (/1, 1, 0, 0/)))
                case(empty)
                    select case(get_species(site + (/0, 2, 0, 0/)))
                    case(empty)
                        call add_proc(Des_002, site + (/0, 1, 0, 0/))
                    case(Pt)
                        call add_proc(Des_006, site + (/0, 1, 0, 0/))
                    end select

                case(Pt)
                    select case(get_species(site + (/0, 2, 0, 0/)))
                    case(empty)
                        call add_proc(Des_010, site + (/0, 1, 0, 0/))
                    case(Pt)
                        call add_proc(Des_014, site + (/0, 1, 0, 0/))
                    end select

                end select

            end select

        end select

        select case(get_species(site + (/-1, 0, 0, 0/)))
        case(Pt)
            select case(get_species(site + (/-1, 0, 1, 0/)))
            case(empty)
                select case(get_species(site + (/-2, 0, 0, 0/)))
                case(empty)
                    select case(get_species(site + (/-1, -1, 0, 0/)))
                    case(empty)
                        call add_proc(Des_004, site + (/-1, 0, 0, 0/))
                    case(Pt)
                        call add_proc(Des_005, site + (/-1, 0, 0, 0/))
                    end select

                case(Pt)
                    select case(get_species(site + (/-1, -1, 0, 0/)))
                    case(empty)
                        call add_proc(Des_006, site + (/-1, 0, 0, 0/))
                    case(Pt)
                        call add_proc(Des_007, site + (/-1, 0, 0, 0/))
                    end select

                end select

            end select

        end select

    end select

    select case(get_species(site + (/1, -1, 0, 0/)))
    case(empty)
        select case(get_species(site + (/0, -1, 0, 0/)))
        case(Pt)
            select case(get_species(site + (/0, -1, 1, 0/)))
            case(empty)
                select case(get_species(site + (/-1, -1, 0, 0/)))
                case(empty)
                    select case(get_species(site + (/0, -2, 0, 0/)))
                    case(empty)
                        call add_proc(Des_000, site + (/0, -1, 0, 0/))
                    case(Pt)
                        call add_proc(Des_001, site + (/0, -1, 0, 0/))
                    end select

                case(Pt)
                    select case(get_species(site + (/0, -2, 0, 0/)))
                    case(empty)
                        call add_proc(Des_002, site + (/0, -1, 0, 0/))
                    case(Pt)
                        call add_proc(Des_003, site + (/0, -1, 0, 0/))
                    end select

                end select

            end select

        end select

        select case(get_species(site + (/1, 0, 0, 0/)))
        case(Pt)
            select case(get_species(site + (/1, 0, 1, 0/)))
            case(empty)
                select case(get_species(site + (/2, 0, 0, 0/)))
                case(empty)
                    select case(get_species(site + (/1, 1, 0, 0/)))
                    case(empty)
                        call add_proc(Des_000, site + (/1, 0, 0, 0/))
                    case(Pt)
                        call add_proc(Des_004, site + (/1, 0, 0, 0/))
                    end select

                case(Pt)
                    select case(get_species(site + (/1, 1, 0, 0/)))
                    case(empty)
                        call add_proc(Des_008, site + (/1, 0, 0, 0/))
                    case(Pt)
                        call add_proc(Des_012, site + (/1, 0, 0, 0/))
                    end select

                end select

            end select

        end select

    case(Pt)
        select case(get_species(site + (/1, 0, 0, 0/)))
        case(Pt)
            select case(get_species(site + (/1, 0, 1, 0/)))
            case(empty)
                select case(get_species(site + (/2, 0, 0, 0/)))
                case(empty)
                    select case(get_species(site + (/1, 1, 0, 0/)))
                    case(empty)
                        call add_proc(Des_001, site + (/1, 0, 0, 0/))
                    case(Pt)
                        call add_proc(Des_005, site + (/1, 0, 0, 0/))
                    end select

                case(Pt)
                    select case(get_species(site + (/1, 1, 0, 0/)))
                    case(empty)
                        call add_proc(Des_009, site + (/1, 0, 0, 0/))
                    case(Pt)
                        call add_proc(Des_013, site + (/1, 0, 0, 0/))
                    end select

                end select

            end select

        end select

        select case(get_species(site + (/0, -1, 0, 0/)))
        case(Pt)
            select case(get_species(site + (/0, -1, 1, 0/)))
            case(empty)
                select case(get_species(site + (/-1, -1, 0, 0/)))
                case(empty)
                    select case(get_species(site + (/0, -2, 0, 0/)))
                    case(empty)
                        call add_proc(Des_008, site + (/0, -1, 0, 0/))
                    case(Pt)
                        call add_proc(Des_009, site + (/0, -1, 0, 0/))
                    end select

                case(Pt)
                    select case(get_species(site + (/0, -2, 0, 0/)))
                    case(empty)
                        call add_proc(Des_010, site + (/0, -1, 0, 0/))
                    case(Pt)
                        call add_proc(Des_011, site + (/0, -1, 0, 0/))
                    end select

                end select

            end select

        end select

    end select


end subroutine take_Pt_default_sc

subroutine put_sub_default_sc(site)

    integer(kind=iint), dimension(4), intent(in) :: site

    ! update lattice
    call replace_species(site, empty, sub)

    ! disable affected processes
    if(avail_sites(Ads, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(Ads, site)
    endif

    if(avail_sites(Ads_sub, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(Ads_sub, site)
    endif

    if(avail_sites(Des_000, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (-1), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_000, site + (/0, 0, -1, 0/))
    endif

    if(avail_sites(Des_000, lattice2nr(site(1) + (-1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_000, site + (/-1, 0, 0, 0/))
    endif

    if(avail_sites(Des_000, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_000, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(Des_000, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_000, site + (/1, 0, 0, 0/))
    endif

    if(avail_sites(Des_000, lattice2nr(site(1) + (0), site(2) + (1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_000, site + (/0, 1, 0, 0/))
    endif

    if(avail_sites(Des_001, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (-1), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_001, site + (/0, 0, -1, 0/))
    endif

    if(avail_sites(Des_001, lattice2nr(site(1) + (-1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_001, site + (/-1, 0, 0, 0/))
    endif

    if(avail_sites(Des_001, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_001, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(Des_001, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_001, site + (/1, 0, 0, 0/))
    endif

    if(avail_sites(Des_002, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (-1), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_002, site + (/0, 0, -1, 0/))
    endif

    if(avail_sites(Des_002, lattice2nr(site(1) + (-1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_002, site + (/-1, 0, 0, 0/))
    endif

    if(avail_sites(Des_002, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_002, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(Des_002, lattice2nr(site(1) + (0), site(2) + (1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_002, site + (/0, 1, 0, 0/))
    endif

    if(avail_sites(Des_003, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (-1), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_003, site + (/0, 0, -1, 0/))
    endif

    if(avail_sites(Des_003, lattice2nr(site(1) + (-1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_003, site + (/-1, 0, 0, 0/))
    endif

    if(avail_sites(Des_003, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_003, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(Des_004, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (-1), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_004, site + (/0, 0, -1, 0/))
    endif

    if(avail_sites(Des_004, lattice2nr(site(1) + (-1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_004, site + (/-1, 0, 0, 0/))
    endif

    if(avail_sites(Des_004, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_004, site + (/1, 0, 0, 0/))
    endif

    if(avail_sites(Des_004, lattice2nr(site(1) + (0), site(2) + (1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_004, site + (/0, 1, 0, 0/))
    endif

    if(avail_sites(Des_005, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (-1), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_005, site + (/0, 0, -1, 0/))
    endif

    if(avail_sites(Des_005, lattice2nr(site(1) + (-1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_005, site + (/-1, 0, 0, 0/))
    endif

    if(avail_sites(Des_005, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_005, site + (/1, 0, 0, 0/))
    endif

    if(avail_sites(Des_006, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (-1), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_006, site + (/0, 0, -1, 0/))
    endif

    if(avail_sites(Des_006, lattice2nr(site(1) + (-1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_006, site + (/-1, 0, 0, 0/))
    endif

    if(avail_sites(Des_006, lattice2nr(site(1) + (0), site(2) + (1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_006, site + (/0, 1, 0, 0/))
    endif

    if(avail_sites(Des_007, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (-1), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_007, site + (/0, 0, -1, 0/))
    endif

    if(avail_sites(Des_007, lattice2nr(site(1) + (-1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_007, site + (/-1, 0, 0, 0/))
    endif

    if(avail_sites(Des_008, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (-1), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_008, site + (/0, 0, -1, 0/))
    endif

    if(avail_sites(Des_008, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_008, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(Des_008, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_008, site + (/1, 0, 0, 0/))
    endif

    if(avail_sites(Des_008, lattice2nr(site(1) + (0), site(2) + (1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_008, site + (/0, 1, 0, 0/))
    endif

    if(avail_sites(Des_009, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (-1), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_009, site + (/0, 0, -1, 0/))
    endif

    if(avail_sites(Des_009, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_009, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(Des_009, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_009, site + (/1, 0, 0, 0/))
    endif

    if(avail_sites(Des_010, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (-1), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_010, site + (/0, 0, -1, 0/))
    endif

    if(avail_sites(Des_010, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_010, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(Des_010, lattice2nr(site(1) + (0), site(2) + (1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_010, site + (/0, 1, 0, 0/))
    endif

    if(avail_sites(Des_011, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (-1), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_011, site + (/0, 0, -1, 0/))
    endif

    if(avail_sites(Des_011, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_011, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(Des_012, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (-1), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_012, site + (/0, 0, -1, 0/))
    endif

    if(avail_sites(Des_012, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_012, site + (/1, 0, 0, 0/))
    endif

    if(avail_sites(Des_012, lattice2nr(site(1) + (0), site(2) + (1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_012, site + (/0, 1, 0, 0/))
    endif

    if(avail_sites(Des_013, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (-1), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_013, site + (/0, 0, -1, 0/))
    endif

    if(avail_sites(Des_013, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_013, site + (/1, 0, 0, 0/))
    endif

    if(avail_sites(Des_014, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (-1), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_014, site + (/0, 0, -1, 0/))
    endif

    if(avail_sites(Des_014, lattice2nr(site(1) + (0), site(2) + (1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_014, site + (/0, 1, 0, 0/))
    endif

    if(avail_sites(Des_015, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (-1), site(4) + (0)), 2).ne.0)then
        call del_proc(Des_015, site + (/0, 0, -1, 0/))
    endif

    ! enable affected processes
    select case(get_species(site + (/0, 0, 1, 0/)))
    case(empty)
        call add_proc(Ads_sub, site + (/0, 0, 1, 0/))
    end select


end subroutine put_sub_default_sc

subroutine take_sub_default_sc(site)

    integer(kind=iint), dimension(4), intent(in) :: site

    ! update lattice
    call replace_species(site, sub, empty)

    ! disable affected processes
    if(avail_sites(Ads_sub, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (1), site(4) + (0)), 2).ne.0)then
        call del_proc(Ads_sub, site + (/0, 0, 1, 0/))
    endif

    ! enable affected processes
    select case(get_species(site + (/0, 0, -1, 0/)))
    case(sub)
        call add_proc(Ads_sub, site)
    case(Pt)
        call add_proc(Ads, site)
        select case(get_species(site + (/1, 0, -1, 0/)))
        case(empty)
            select case(get_species(site + (/0, 1, -1, 0/)))
            case(empty)
                select case(get_species(site + (/-1, 0, -1, 0/)))
                case(empty)
                    select case(get_species(site + (/0, -1, -1, 0/)))
                    case(empty)
                        call add_proc(Des_000, site + (/0, 0, -1, 0/))
                    case(Pt)
                        call add_proc(Des_001, site + (/0, 0, -1, 0/))
                    end select

                case(Pt)
                    select case(get_species(site + (/0, -1, -1, 0/)))
                    case(empty)
                        call add_proc(Des_002, site + (/0, 0, -1, 0/))
                    case(Pt)
                        call add_proc(Des_003, site + (/0, 0, -1, 0/))
                    end select

                end select

            case(Pt)
                select case(get_species(site + (/-1, 0, -1, 0/)))
                case(empty)
                    select case(get_species(site + (/0, -1, -1, 0/)))
                    case(empty)
                        call add_proc(Des_004, site + (/0, 0, -1, 0/))
                    case(Pt)
                        call add_proc(Des_005, site + (/0, 0, -1, 0/))
                    end select

                case(Pt)
                    select case(get_species(site + (/0, -1, -1, 0/)))
                    case(empty)
                        call add_proc(Des_006, site + (/0, 0, -1, 0/))
                    case(Pt)
                        call add_proc(Des_007, site + (/0, 0, -1, 0/))
                    end select

                end select

            end select

        case(Pt)
            select case(get_species(site + (/0, 1, -1, 0/)))
            case(empty)
                select case(get_species(site + (/-1, 0, -1, 0/)))
                case(empty)
                    select case(get_species(site + (/0, -1, -1, 0/)))
                    case(empty)
                        call add_proc(Des_008, site + (/0, 0, -1, 0/))
                    case(Pt)
                        call add_proc(Des_009, site + (/0, 0, -1, 0/))
                    end select

                case(Pt)
                    select case(get_species(site + (/0, -1, -1, 0/)))
                    case(empty)
                        call add_proc(Des_010, site + (/0, 0, -1, 0/))
                    case(Pt)
                        call add_proc(Des_011, site + (/0, 0, -1, 0/))
                    end select

                end select

            case(Pt)
                select case(get_species(site + (/-1, 0, -1, 0/)))
                case(empty)
                    select case(get_species(site + (/0, -1, -1, 0/)))
                    case(empty)
                        call add_proc(Des_012, site + (/0, 0, -1, 0/))
                    case(Pt)
                        call add_proc(Des_013, site + (/0, 0, -1, 0/))
                    end select

                case(Pt)
                    select case(get_species(site + (/0, -1, -1, 0/)))
                    case(empty)
                        call add_proc(Des_014, site + (/0, 0, -1, 0/))
                    case(Pt)
                        call add_proc(Des_015, site + (/0, 0, -1, 0/))
                    end select

                end select

            end select

        end select

    end select

    select case(get_species(site + (/-1, 1, 0, 0/)))
    case(empty)
        select case(get_species(site + (/-1, 0, 0, 0/)))
        case(Pt)
            select case(get_species(site + (/-1, 0, 1, 0/)))
            case(empty)
                select case(get_species(site + (/-2, 0, 0, 0/)))
                case(empty)
                    select case(get_species(site + (/-1, -1, 0, 0/)))
                    case(empty)
                        call add_proc(Des_000, site + (/-1, 0, 0, 0/))
                    case(Pt)
                        call add_proc(Des_001, site + (/-1, 0, 0, 0/))
                    end select

                case(Pt)
                    select case(get_species(site + (/-1, -1, 0, 0/)))
                    case(empty)
                        call add_proc(Des_002, site + (/-1, 0, 0, 0/))
                    case(Pt)
                        call add_proc(Des_003, site + (/-1, 0, 0, 0/))
                    end select

                end select

            end select

        end select

        select case(get_species(site + (/0, 1, 0, 0/)))
        case(Pt)
            select case(get_species(site + (/0, 1, 1, 0/)))
            case(empty)
                select case(get_species(site + (/1, 1, 0, 0/)))
                case(empty)
                    select case(get_species(site + (/0, 2, 0, 0/)))
                    case(empty)
                        call add_proc(Des_000, site + (/0, 1, 0, 0/))
                    case(Pt)
                        call add_proc(Des_004, site + (/0, 1, 0, 0/))
                    end select

                case(Pt)
                    select case(get_species(site + (/0, 2, 0, 0/)))
                    case(empty)
                        call add_proc(Des_008, site + (/0, 1, 0, 0/))
                    case(Pt)
                        call add_proc(Des_012, site + (/0, 1, 0, 0/))
                    end select

                end select

            end select

        end select

    case(Pt)
        select case(get_species(site + (/0, 1, 0, 0/)))
        case(Pt)
            select case(get_species(site + (/0, 1, 1, 0/)))
            case(empty)
                select case(get_species(site + (/1, 1, 0, 0/)))
                case(empty)
                    select case(get_species(site + (/0, 2, 0, 0/)))
                    case(empty)
                        call add_proc(Des_002, site + (/0, 1, 0, 0/))
                    case(Pt)
                        call add_proc(Des_006, site + (/0, 1, 0, 0/))
                    end select

                case(Pt)
                    select case(get_species(site + (/0, 2, 0, 0/)))
                    case(empty)
                        call add_proc(Des_010, site + (/0, 1, 0, 0/))
                    case(Pt)
                        call add_proc(Des_014, site + (/0, 1, 0, 0/))
                    end select

                end select

            end select

        end select

        select case(get_species(site + (/-1, 0, 0, 0/)))
        case(Pt)
            select case(get_species(site + (/-1, 0, 1, 0/)))
            case(empty)
                select case(get_species(site + (/-2, 0, 0, 0/)))
                case(empty)
                    select case(get_species(site + (/-1, -1, 0, 0/)))
                    case(empty)
                        call add_proc(Des_004, site + (/-1, 0, 0, 0/))
                    case(Pt)
                        call add_proc(Des_005, site + (/-1, 0, 0, 0/))
                    end select

                case(Pt)
                    select case(get_species(site + (/-1, -1, 0, 0/)))
                    case(empty)
                        call add_proc(Des_006, site + (/-1, 0, 0, 0/))
                    case(Pt)
                        call add_proc(Des_007, site + (/-1, 0, 0, 0/))
                    end select

                end select

            end select

        end select

    end select

    select case(get_species(site + (/1, -1, 0, 0/)))
    case(empty)
        select case(get_species(site + (/0, -1, 0, 0/)))
        case(Pt)
            select case(get_species(site + (/0, -1, 1, 0/)))
            case(empty)
                select case(get_species(site + (/-1, -1, 0, 0/)))
                case(empty)
                    select case(get_species(site + (/0, -2, 0, 0/)))
                    case(empty)
                        call add_proc(Des_000, site + (/0, -1, 0, 0/))
                    case(Pt)
                        call add_proc(Des_001, site + (/0, -1, 0, 0/))
                    end select

                case(Pt)
                    select case(get_species(site + (/0, -2, 0, 0/)))
                    case(empty)
                        call add_proc(Des_002, site + (/0, -1, 0, 0/))
                    case(Pt)
                        call add_proc(Des_003, site + (/0, -1, 0, 0/))
                    end select

                end select

            end select

        end select

        select case(get_species(site + (/1, 0, 0, 0/)))
        case(Pt)
            select case(get_species(site + (/1, 0, 1, 0/)))
            case(empty)
                select case(get_species(site + (/2, 0, 0, 0/)))
                case(empty)
                    select case(get_species(site + (/1, 1, 0, 0/)))
                    case(empty)
                        call add_proc(Des_000, site + (/1, 0, 0, 0/))
                    case(Pt)
                        call add_proc(Des_004, site + (/1, 0, 0, 0/))
                    end select

                case(Pt)
                    select case(get_species(site + (/1, 1, 0, 0/)))
                    case(empty)
                        call add_proc(Des_008, site + (/1, 0, 0, 0/))
                    case(Pt)
                        call add_proc(Des_012, site + (/1, 0, 0, 0/))
                    end select

                end select

            end select

        end select

    case(Pt)
        select case(get_species(site + (/1, 0, 0, 0/)))
        case(Pt)
            select case(get_species(site + (/1, 0, 1, 0/)))
            case(empty)
                select case(get_species(site + (/2, 0, 0, 0/)))
                case(empty)
                    select case(get_species(site + (/1, 1, 0, 0/)))
                    case(empty)
                        call add_proc(Des_001, site + (/1, 0, 0, 0/))
                    case(Pt)
                        call add_proc(Des_005, site + (/1, 0, 0, 0/))
                    end select

                case(Pt)
                    select case(get_species(site + (/1, 1, 0, 0/)))
                    case(empty)
                        call add_proc(Des_009, site + (/1, 0, 0, 0/))
                    case(Pt)
                        call add_proc(Des_013, site + (/1, 0, 0, 0/))
                    end select

                end select

            end select

        end select

        select case(get_species(site + (/0, -1, 0, 0/)))
        case(Pt)
            select case(get_species(site + (/0, -1, 1, 0/)))
            case(empty)
                select case(get_species(site + (/-1, -1, 0, 0/)))
                case(empty)
                    select case(get_species(site + (/0, -2, 0, 0/)))
                    case(empty)
                        call add_proc(Des_008, site + (/0, -1, 0, 0/))
                    case(Pt)
                        call add_proc(Des_009, site + (/0, -1, 0, 0/))
                    end select

                case(Pt)
                    select case(get_species(site + (/0, -2, 0, 0/)))
                    case(empty)
                        call add_proc(Des_010, site + (/0, -1, 0, 0/))
                    case(Pt)
                        call add_proc(Des_011, site + (/0, -1, 0, 0/))
                    end select

                end select

            end select

        end select

    end select


end subroutine take_sub_default_sc

subroutine touchup_default_sc(site)

    integer(kind=iint), dimension(4), intent(in) :: site

    if (can_do(Ads, site)) then
        call del_proc(Ads, site)
    endif
    if (can_do(Ads_sub, site)) then
        call del_proc(Ads_sub, site)
    endif
    if (can_do(Des_000, site)) then
        call del_proc(Des_000, site)
    endif
    if (can_do(Des_001, site)) then
        call del_proc(Des_001, site)
    endif
    if (can_do(Des_002, site)) then
        call del_proc(Des_002, site)
    endif
    if (can_do(Des_003, site)) then
        call del_proc(Des_003, site)
    endif
    if (can_do(Des_004, site)) then
        call del_proc(Des_004, site)
    endif
    if (can_do(Des_005, site)) then
        call del_proc(Des_005, site)
    endif
    if (can_do(Des_006, site)) then
        call del_proc(Des_006, site)
    endif
    if (can_do(Des_007, site)) then
        call del_proc(Des_007, site)
    endif
    if (can_do(Des_008, site)) then
        call del_proc(Des_008, site)
    endif
    if (can_do(Des_009, site)) then
        call del_proc(Des_009, site)
    endif
    if (can_do(Des_010, site)) then
        call del_proc(Des_010, site)
    endif
    if (can_do(Des_011, site)) then
        call del_proc(Des_011, site)
    endif
    if (can_do(Des_012, site)) then
        call del_proc(Des_012, site)
    endif
    if (can_do(Des_013, site)) then
        call del_proc(Des_013, site)
    endif
    if (can_do(Des_014, site)) then
        call del_proc(Des_014, site)
    endif
    if (can_do(Des_015, site)) then
        call del_proc(Des_015, site)
    endif
    select case(get_species(site))
    case(empty)
        select case(get_species(site + (/0, 0, -1, 0/)))
        case(sub)
            call add_proc(Ads_sub, site)
        case(Pt)
            call add_proc(Ads, site)
        end select

    case(Pt)
        select case(get_species(site + (/0, 0, 1, 0/)))
        case(empty)
            select case(get_species(site + (/1, 0, 0, 0/)))
            case(empty)
                select case(get_species(site + (/0, 1, 0, 0/)))
                case(empty)
                    select case(get_species(site + (/-1, 0, 0, 0/)))
                    case(empty)
                        select case(get_species(site + (/0, -1, 0, 0/)))
                        case(empty)
                            call add_proc(Des_000, site)
                        case(Pt)
                            call add_proc(Des_001, site)
                        end select

                    case(Pt)
                        select case(get_species(site + (/0, -1, 0, 0/)))
                        case(empty)
                            call add_proc(Des_002, site)
                        case(Pt)
                            call add_proc(Des_003, site)
                        end select

                    end select

                case(Pt)
                    select case(get_species(site + (/-1, 0, 0, 0/)))
                    case(empty)
                        select case(get_species(site + (/0, -1, 0, 0/)))
                        case(empty)
                            call add_proc(Des_004, site)
                        case(Pt)
                            call add_proc(Des_005, site)
                        end select

                    case(Pt)
                        select case(get_species(site + (/0, -1, 0, 0/)))
                        case(empty)
                            call add_proc(Des_006, site)
                        case(Pt)
                            call add_proc(Des_007, site)
                        end select

                    end select

                end select

            case(Pt)
                select case(get_species(site + (/0, 1, 0, 0/)))
                case(empty)
                    select case(get_species(site + (/-1, 0, 0, 0/)))
                    case(empty)
                        select case(get_species(site + (/0, -1, 0, 0/)))
                        case(empty)
                            call add_proc(Des_008, site)
                        case(Pt)
                            call add_proc(Des_009, site)
                        end select

                    case(Pt)
                        select case(get_species(site + (/0, -1, 0, 0/)))
                        case(empty)
                            call add_proc(Des_010, site)
                        case(Pt)
                            call add_proc(Des_011, site)
                        end select

                    end select

                case(Pt)
                    select case(get_species(site + (/-1, 0, 0, 0/)))
                    case(empty)
                        select case(get_species(site + (/0, -1, 0, 0/)))
                        case(empty)
                            call add_proc(Des_012, site)
                        case(Pt)
                            call add_proc(Des_013, site)
                        end select

                    case(Pt)
                        select case(get_species(site + (/0, -1, 0, 0/)))
                        case(empty)
                            call add_proc(Des_014, site)
                        case(Pt)
                            call add_proc(Des_015, site)
                        end select

                    end select

                end select

            end select

        end select

    end select

end subroutine touchup_default_sc

end module proclist
